services:
  app:
    build: .
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/userdb
      - SPRING_DATA_MONGODB_DATABASE=userdb
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=userdb

volumes:
  mongo-data:
